development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project_one_development
  pool: 5
  username: root
  password: root
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project_one_test
  pool: 5
  username: root
  password: root
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: project_one_production
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
